# get packages
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure packages are installed using apt
  apt:
    name: "{{ packages }}"
    state: present
  when:
    - not update_ubuntu

- name: Ensure packages are in latest state
  apt:
    name: "{{ packages }}"
    state: latest

- name: Install reccomended packages
  apt:
    install_recommends: yes

- name: Ensure Radix packages are installed
  apt:
    name: "{{ radix_packages }}"
    state: present
  when:
    - not update_radix

- name: Ensure Radix packages are in latest state
  apt:
    name: "{{ radix_packages }}"
    state: latest
  when:
    - update_radix