# get packages
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure docker packages are installed using apt
  apt:
    name: "{{ docker_packages }}"
    state: present
  when:
    - not update_ubuntu
    - docker_install

- name: Ensure systemd packages are installed using apt
  apt:
    name: "{{ systemd_packages }}"
    state: present
  when:
    - not update_ubuntu
    - systemd_install

- name: Ensure docker packages are in latest state
  apt:
    name: "{{ docker_packages }}"
    state: latest

- name: Ensure systemd packages are in latest state
  apt:
    name: "{{ systemd_packages }}"
    state: latest

- name: Install reccomended packages
  apt:
    install_recommends: yes

- name: Ensure Radix packages are installed
  apt:
    name: "{{ radix_packages }}"
    state: present
  when:
    - not update_radix

- name: Ensure Radix packages are in latest state
  apt:
    name: "{{ radix_packages }}"
    state: latest
  when:
    - update_radix

- name: Ensure pip3 is available
  apt:
    name: "python3-pip"
    update_cache: yes
    state: present
  delegate_to: localhost
  when: 
    - docker_install

- name: Ensure pip packages are present on localhost
  pip:
    name: "{{ pip_packages }}"
    state: present
  delegate_to: localhost
  when: 
    - docker_install

- name: Ensure pip packages are present on radix-node.
  pip:
    name: "{{ pip_packages }}"
    state: present
  when: 
    - docker_install