# Generate passwords
- name: Generate 16 character password for radix_node_password
  set_fact:
    radix_node_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=16') }}"

- name: Generate 16 character password for radix_nginx_password
  set_fact:
    radix_nginx_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=16') }}"

- name: Generate 16 character password for radix_nginx_superadmin_password
  set_fact:
    radix_nginx_superadmin_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=16') }}"

- name: Generate 16 character password for radix_keystore_password
  set_fact:
    radix_keystore_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=16') }}"

- name: Generate 16 character password for radix_metrics_password
  set_fact:
    radix_metrics_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=16') }}"

- name: Debug the passwords so the user can store them
  debug:
    msg:
      - "radix_node_password: {{ radix_node_password }}"
      - "radix_nginx_password: {{ radix_nginx_password }}"
      - "radix_nginx_superadmin_password: {{ radix_nginx_superadmin_password }}"
      - "radix_keystore_password: {{ radix_keystore_password }}"
      - "radix_metrics_password: {{ radix_metrics_password }}"