# Make sure the radix_user exists
- name: Create radixdlt group
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "radixdlt"
    - "docker"

- name: Create radix_user, including Docker group membership
  user:
    name: "{{ radix_user }}"
    groups: "sudo,docker,{{ radix_user }}"
    state: present
    shell: "/bin/bash"
  when: docker_install

- name: Create radix_user, without Docker and sudo group membership
  user:
    name: "{{ radix_user }}"
    groups: "radixdlt"
    state: present
    shell: "/bin/bash"
  when: systemd_install

# Set radix_network_node variable to prep the environment file
- name: Set radix_network_node variable when radix_node_region is set to asia-sout
  set_fact:
    radix_network_node: "{{ radix_node_asia_pacific }}"
  when: radix_node_region == "asia-south"

- name: Set radix_network_node variable when radix_node_region is set to asia-sout-east
  set_fact:
    radix_network_node: "{{ radix_node_asia_pacific_south }}"
  when: radix_node_region == "asia-south-east"

- name: Set radix_network_node variable when radix_node_region is set to eu-west
  set_fact:
    radix_network_node: "{{ radix_node_eu_west }}"
  when: radix_node_region == "eu-west"

- name: Set radix_network_node variable when radix_node_region is set to us-east
  set_fact:
    radix_network_node: "{{ radix_node_us_east }}"
  when: radix_node_region == "us-east"

# Sudo access for radix_user
- name: Allow sudo users to sudo without a password
  copy:
    dest: "/etc/sudoers.d/{{ radix_user }}"
    mode: 0440
    content: "{{ radix_user }} ALL=(ALL) NOPASSWD: ALL"

- name: Check if .bash_aliases exists
  stat:
    path: "/home/{{ radix_user }}/.bash_aliases"
  register: stat_result

# When .bash_aliases does not exist:
- name: Export environment variables
  template:
    src: "templates/.environment.j2"
    dest: "/home/{{ radix_user }}/.bash_aliases"
    owner: "{{ radix_user }}"
    remote_src: false
  when: not stat_result.stat.exists
  become: true
  become_user: "{{ radix_user }}"

# When .bash_aliases does exist:
- template:
    src: "templates/.environment.j2"
    dest: "/home/{{ radix_user }}/.bash_aliases_prep"
    owner: "{{ radix_user }}"
  when: stat_result.stat.exists

# Append to bash_rc
- name: Append to .bash_aliases
  lineinfile:
    dest: "/home/{{ radix_user }}/.bash_aliases"
    line: "source /home/{{ radix_user }}/.bash_aliases_prep"
    state: present
  when: stat_result.stat.exists