---
- name: Fail if not Ubuntu 20.04
  set_fact:
    distro: "{{ ansible_distribution_version }}"

- name: Fail if distribution version does not equal to 20.04
  fail:
    msg: "This Ansible role is only supported on Ubuntu 20.04"
  when: distro != "20.04"

- name: Fail if fullnode and archive are both set to true.
  fail:
    msg: "Variables 'fullnode' and 'acrhive' cannot both be set to 'true'."
  when: 
    - fullnode
    - archive

- name: Fail if radix_network_id is not set to 'S' or 'M'.
  fail:
    msg: "Variable radix_network_id must be set to 'S' or 'M'."
  when: radix_network_id is not in ["s", "m"]

- name: Fail if radix_node_region is not set to 'eu-west', 'asia-south', 'asia-south-east', 'eu-west', or 'us-east'.
  fail:
    msg: "Variable 'radix_node_region' must be set to 'eu-west', 'asia-south', 'asia-south-east', 'eu-west', or 'us-east'."
  when: radix_node_region is not in ["eu-west", "asia-south", "asia-south-east", "eu-west", "us-east"]

- name: Fail if docker_install is true and 'systemd_install' is true.
  fail:
    msg: "Variable 'docker_install' and 'systemd_install' cannot both be set to 'true'."
  when: 
    - docker_install
    - systemd_install