Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end

      $script = <<-SCRIPT
      sudo apt-get update
      sudo apt-get install -y software-properties-common
      wget -O radixnode https://github.com/radixdlt/node-runner/releases/download/1.0.4/radixnode-ubuntu-20.04
      sudo chmod +x radixnode && sudo mv radixnode /usr/local/bin
      SCRIPT

      config.vm.provision "shell", inline: $script, privileged: false

  end
  